version: "3.6"

services:
  proton:
    build:
      context: ./proton
    environment:
      - COUNTRY_CODE=US
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    command: /bin/sh -c "protonvpn connect --cc $${COUNTRY_CODE} && watch -n 600 protonvpn status 2>/dev/null"
    # command: /bin/sh -c "protonvpn connect -r && watch -n 600 protonvpn status 2>/dev/null"
    stdin_open: true
    tty: true
    restart: "unless-stopped"
    networks:
      static-network:
        ipv4_address: 172.20.128.2
    ports:
      - "127.0.0.1:9194:1194/tcp"
      - "127.0.0.1:9194:1194/udp"
      - "127.0.0.1:8080:80/tcp"
      - "127.0.0.1:8443:443/tcp"

  pritunl:
    image: jippi/pritunl
    volumes:
      - ./pritunl/pritunl:/var/lib/pritunl
      - ./pritunl/mongodb:/var/lib/mongodb
      - ./pritunl/pritunl.conf:/etc/pritunl.conf
    depends_on:
      - proton
      - pihole
    network_mode: service:proton
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  pihole:
    build:
      context: ./pihole
    networks:
      static-network:
        ipv4_address: 172.20.128.3
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: $PIHOLE_PASSWORD
      VIRTUAL_HOST: $PIHOLE_VIRTUAL_HOST
    command: /bin/sh -c 'ip route add 192.168.245.0/24 via 172.20.128.2 && /s6-init'
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
