services:
  vpn:
    build:
      context: ./proton
      args:
        - PROTONVPN_USER=$PROTONVPN_USER
        - PROTONVPN_PASSWORD=$PROTONVPN_PASSWORD
        - PROTONVPN_PLAN=$PROTONVPN_PLAN
        - PROTONVPN_PROTOCOL=$PROTONVPN_PROTOCOL
    environment:
      - COUNTRY_CODE=US
    command: /bin/sh -c "protonvpn connect --cc $${COUNTRY_CODE} && watch -n 600 protonvpn status 2>/dev/null"
    # If we want to get really crazy, connect to a random server worldwide
    # command: /bin/sh -c "protonvpn connect -r && watch -n 600 protonvpn status 2>/dev/null"
