version: "3.6"

services:
  vpn:
    build:
      context: ./vpn
    environment:
      - COUNTRY_CODE=US
      # - COUNTRY_CODE=CH
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    command: /bin/sh -c "protonvpn connect --cc $${COUNTRY_CODE} && watch -n 5 protonvpn status 2>/dev/null"
    stdin_open: true
    tty: true
    restart: "unless-stopped"
    # ports:
      # - "127.0.0.1:6881-6999:6881-6999"
    ports:
      - "127.0.0.1:9194:1194/tcp"
      - "127.0.0.1:9194:1194/udp"
      - "127.0.0.1:8080:80/tcp"
      - "127.0.0.1:8443:443/tcp"

  pritunl:
    image: jippi/pritunl
    environment:
      - PRITUNL_DEBUG=true
    volumes:
      - ./pritunl/pritunl:/var/lib/pritunl
      - ./pritunl/mongodb:/var/lib/mongodb
      - ./pritunl/pritunl.conf:/etc/pritunl.conf
    depends_on:
      - vpn
    network_mode: service:vpn
    cap_add:
      - NET_ADMIN
    # privileged: true
