version: "3.6"

services:
  proton:
    build:
      context: ./proton
    environment:
      - COUNTRY_CODE=US
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    command: /bin/sh -c "protonvpn connect --cc $${COUNTRY_CODE} && watch -n 5 protonvpn status 2>/dev/null"
    stdin_open: true
    tty: true
    restart: "unless-stopped"
    networks:
      static-network:
        ipv4_address: 172.20.128.2
    ports:
      - "127.0.0.1:9194:1194/tcp"
      - "127.0.0.1:9194:1194/udp"
      - "127.0.0.1:8080:80/tcp"
      - "127.0.0.1:8443:443/tcp"

  softether:
    image: siomiz/softethervpn
    environment:
      - SPW=$SOFTETHER_SPW
      - HPW=$SOFTETHER_HPW
    volumes:
      - ./softether/vpn_server.config:/usr/vpnserver/vpn_server.config
    depends_on:
      - proton
      - pihole
    network_mode: service:proton
    cap_add:
      - NET_ADMIN

  pihole:
    image: pihole/pihole:latest
    networks:
      static-network:
        ipv4_address: 172.20.128.3
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "127.0.0.1:9091:80/tcp"
      # - "53:53/tcp"
      # - "53:53/udp"
    #   - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
    #   - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: $PIHOLE_PASSWORD
      VIRTUAL_HOST: $VIRTUAL_HOST
    # Volumes store your data between container upgrades
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
